version: "3"
services: 
  app:
    build: .
    volumes: 
      - .:/home
    command: ["stdbuf", "-oL", "python3", "test1.py"]
    working_dir: /home
    restart: always
  web:
    image: httpd
    volumes: 
      - ./public-html/:/usr/local/apache2/htdocs/
    ports:
      - 80:80
    restart: always
