version: "3"
services: 
  app:
    build: .
    volumes: 
      - .:/home
    command: python3 test1.py
    working_dir: /home
  web:
    image: httpd
    volumes: 
      - ./public-html/:/usr/local/apache2/htdocs/
    ports:
      - 8080:80
