version: "3"
services: 
  app:
    build: .
    volumes: 
      - .:/home
    command: ["stdbuf", "-oL", "python3", "test1.py"]
    working_dir: /home
    restart: always
  web:
    image: httpd
    volumes: 
      - ./public-html/:/usr/local/apache2/htdocs/
    ports:
<<<<<<< HEAD
      - 80:80
=======
      - 8080:80
>>>>>>> 517329e229646190cc8e4156afe975e54b524a51
    restart: always
